name: 'reactApp'
on:
  push:
    branches:
      - "**"
  pull_request:
    types: 
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
 npm-build-and-publish:
   runs-on: ubuntu-latest
   env:
     BUILD_NAME: 'reactApp'
     JFROG_BUILD_STATUS: PASS
   steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: JFrog CLI setup ðŸ¸
       uses: jfrog/setup-jfrog-cli@v4
       env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        JF_USER: ${{secrets.JF_USER}}
        JF_ACCESS_TOKEN: ${{secrets.JF_ACCESS_TOKEN}}
        DOCKER_JF_RT_REPO: ${{secrets.DOCKER_JF_RT_REPO}}
        NPM_JF_RT_REPO: ${{secrets.NPM_JF_RT_REPO}}
        HOST: ${{secrets.HOST}}
     - name: Health check JFrog Artifactory instance ðŸ¸
       run: |
        jf --version
        # jf rt ping
        # jf config show
      
     - name: "Curation: audit" # https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/cli-for-jfrog-security/cli-for-jfrog-curation
       timeout-minutes: 15    # ref https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes
       continue-on-error: true    # ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
       run: |
        jf ca --format=table --threads=10
     
     - name: Build and publish
       run: |
         # Configure the project
         jf npmc --repo-resolve alpha-npm-virtual --repo-deploy alpha-npm-virtual
         # Build the project using JFrog CLI
         jf npm install --build-name ${{env.BUILD_NAME}} --build-number ${{github.run_number}}
         jf npm publish --build-name ${{env.BUILD_NAME}} --build-number ${{github.run_number}}
        #  npm test -- --json --outputFile=jest-report-${{github.run_number}}.json

 # Call the reusable workflow
 docker-build-push:
    uses: ./.github/workflows/docker-build-push.yml
    needs: npm-build-and-publish
    with:
      image_name: "reactappimage"
      build_number: ${{ github.run_number }}
    secrets:
      JF_URL: ${{ secrets.JF_URL }}
      JF_USER: ${{ secrets.JF_USER }}
      JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      
 
 publish-build-build-info:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: JFrog CLI setup ðŸ¸
        uses: jfrog/setup-jfrog-cli@v4
        env:
         JF_URL: ${{ secrets.JF_URL }}
         JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
         JF_USER: ${{secrets.JF_USER}}
         JF_ACCESS_TOKEN: ${{secrets.JF_ACCESS_TOKEN}}
         DOCKER_JF_RT_REPO: ${{secrets.DOCKER_JF_RT_REPO}}
         NPM_JF_RT_REPO: ${{secrets.NPM_JF_RT_REPO}}
      - name: Do something after everything is done
        run: |
         # Collect and store environment variables in the build-info
         jf rt bce ${{env.BUILD_NAME}} ${{github.run_number}}
         # Collect and store VCS details in the build-info
         jf rt bag ${{env.BUILD_NAME}} ${{github.run_number}}
         # Publish the build-info to Artifactory
         jf rt bp ${{env.BUILD_NAME}} ${{github.run_number}}
         # Scan the published build-info with Xray
         jf rt bs ${{env.BUILD_NAME}} ${{github.run_number}}
        if: always()
     
     

     # - name: Create Release Bundle for RLM
     #   run: |
     #     jf rbc --builds=json/builds-spec.json --signing-key=${{ secrets.Key }} reactApp ${{github.run_number}}

     #     # promote to Dev
     #     jf rbp reactApp ${{ github.run_number}} DEV --signing-key=${{ secrets.Key }} --include-repos=alpha-npm-dev-local
     #     jf rt set-props "alpha-npm-dev-local/react-bank-api/-/react-bank-api-1.0.23.tgz" "unit.test=pass;integration.test=null;"
         

     #     # Promote to QA
     #     jf rbp reactApp ${{ github.run_number }} QA --signing-key=${{ secrets.Key }} --include-repos=alpha-npm-qa-local

     #     jf rt set-props "alpha-npm-qa-local/react-bank-api/-/react-bank-api-1.0.23.tgz" "unit.test=pass;integration.test=pass;"

     #     # Promote to PROD
     #     jf rbp reactApp ${{ github.run_number }} PROD --signing-key=${{ secrets.Key }} --include-repos=alpha-npm-prod-local

     # - name: Failure check
     #   run: |
     #     echo "JFROG_BUILD_STATUS=FAIL" >> $GITHUB_ENV
     #   if: failure()
